### ISSUE TITLE
Where to find havoc_dlls ?

### ISSUE THREAD

**Issue by yxliang01** [boogie-org/symdiff#3]
Hello,

Thanks for making symdiff. However, I'm having difficulty to run it. The C frontend looks like depending on the havoc dlls, but it doesn't look like in this project. May I know where I can get the havoc dlls?

Thanks

**Comment by shuvendu-lahiri** [comment]
SymDiff open source primarily targets a Boogie file as inputs. There was earlier work on supporting C using HAVOC dlls, that you are welcome to try, but we are no longer patching it. Follow the documentation page for  https://github.com/boogie-org/symdiff/blob/master/docs/C_Front_End.md, which will take you to SymDiff webpage, and you can see a download link, which should get you https://www.microsoft.com/en-us/download/confirmation.aspx?id=52364.
