### ISSUE TITLE
Building with modern tools

### ISSUE THREAD

**Issue by markxb** [boogie-org/symdiff#4]
Hello,
I am interested in using SymDiff in a project, but I ran into issues when trying to build the project. I have tried to build the project using dotnet, older mono and Visual Studio to no avail. I noticed the build instructions mentioned using Visual Studio 2013, which I'm not sure I'll be able to run in my current set up (M1 mac), so that is not something I have tried.
I was wondering if there is anything I can do to help get this project building and if there are any pointers for updating the project.

Thanks,
Mark

**Comment by rakamaric** [comment]
@shuvendu-lahiri Any chance we could get help with this? Thanks!
